package raft


// TODO: STEP 1 -> SINGLE NODE WITH A LOG

// TODO: STEP 2 -> TRANSPORT NEEDS TO HAVE PEER DESCOVERY

//TODO: STEP 3 -> HEARTBREAT

// TODO: LEADER ELECTION

// TODO: SPLIT VOTE

// TODO: MESSAGE LOGGING AND DISTRIBUTION (LOG REPLICATION)

